### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by schub** [robertbuecker/nessundorma#1]
Hey Robert,

can't get it to work. Could you please provide a working example e.g. a link to a google spreadsheet that works?

I created a really simple spreadsheet just with instructions for Arka but get some errors...

Running the program is like: 

`./tbl2json.py https://docs.google.com/spreadsheets/d/1c4OEWhuiwl5ivFOCzGWi3M9RZKKn9mQDIJ0FX-invJU/edit?usp=sharing`

**Comment by robertbuecker** [comment]
Hey, omit everything past the final slash of the URL, and add the output file:
`./tbl2json.py https://docs.google.com/spreadsheets/d/1c4OEWhuiwl5ivFOCzGWi3M9RZKKn9mQDIJ0FX-invJU story.json`

**Comment by schub** [comment]
Great... that did the job.. Thx 👍
