### ISSUE TITLE
Request for naming properties

### ISSUE THREAD

**Issue by schub** [robertbuecker/nessundorma#2]
Could we aggree that property names produced in the final json do not contain spaces?

concrete: 

```
{
      "overall audio": null,
      "overall light": null,
      "beamer commentar": null
}
```

change into: 

```
{
      "overallAudio": null,
      "overallLight": null,
      "beamerCommentar": null
}
```

This makes things easier in parsing the stuff...

**Comment by robertbuecker** [comment]
That just needs a change of the column title in the original table, the JSON keys are generated from that. Will complain to the CEO ;-).

Am 20.11.2020 um 16:17 schrieb Markus Schubert <notifications@github.com<mailto:notifications@github.com>>:



Could we aggree that property names produced in the final json do not contain spaces?

concrete:

{
      "overall audio": null,
      "overall light": null,
      "beamer commentar": null
}


change into:

{
      "overallAudio": null,
      "overallLight": null,
      "beamerCommentar": null
}


This makes things easier in parsing the stuff...

**Comment by robertbuecker** [comment]
Changed everything existing to camelCase.

Am 20.11.2020 um 16:19 schrieb Robert Bücker <robert.buecker@mpsd.mpg.de<mailto:robert.buecker@mpsd.mpg.de>>:

That just needs a change of the column title in the original table, the JSON keys are generated from that. Will complain to the CEO ;-).

Am 20.11.2020 um 16:17 schrieb Markus Schubert <notifications@github.com<mailto:notifications@github.com>>:



Could we aggree that property names produced in the final json do not contain spaces?

concrete:

{
      "overall audio": null,
      "overall light": null,
      "beamer commentar": null
}


change into:

{
      "overallAudio": null,
      "overallLight": null,
      "beamerCommentar": null
}


This makes things easier in parsing the stuff...

**Comment by schub** [comment]
>That just needs a change of the column title in the original table, the JSON keys are generated from that. Will complain to the CEO ;-).

# 🤣

Great, to extract it from the column names 👍
